const fs = require("fs/promises");
const client = require("../../db");

global.beforeEach(async () => {
  const sqlDataForBooks = await fs.readFile("./sql/create-books.sql");
  const sqlStringForBooks = sqlDataForBooks.toString();

  await client.query(sqlStringForBooks);

  const sqlDataForPets = await fs.readFile("./sql/create-pets.sql");
  const sqlStringForPets = sqlDataForPets.toString();

  await client.query(sqlStringForPets);
});

global.afterAll(
  async () => {
    const sql = `
  INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('voluptatem eligendi cupiditate et', 'Fiction', 'Carolyn Donnelly', 'western', '2020-11-16T21:38:54.789+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('blanditiis consequatur in accusantium autem voluptatem', 'Fiction', 'Carolyn Donnelly', 'western', '2017-05-01T14:06:32.789+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('eligendi consequatur et', 'Fiction', 'Carolyn Donnelly', 'western', '2016-12-24T07:16:51.420+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ut dolor', 'Fiction', 'Colt Dibbert', 'fantasy', '2012-02-04T04:27:29.083+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('excepturi sed nam recusandae ut sed', 'Fiction', 'Colt Dibbert', 'fantasy', '2017-11-13T12:39:13.886+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('voluptatem voluptas ut occaecati', 'Fiction', 'Colt Dibbert', 'fantasy', '2021-09-18T12:40:54.153+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ea provident quisquam aut inventore', 'Fiction', 'Karli Kiehn', 'historical', '2016-02-09T16:22:06.082+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ea et', 'Fiction', 'Kim Hand', 'thriller', '2020-01-30T11:51:58.233+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('aliquam totam est quasi', 'Fiction', 'Kim Hand', 'thriller', '2011-06-03T16:34:20.912+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('facere dolor velit eaque', 'Fiction', 'Kim Hand', 'thriller', '2007-03-03T06:10:13.134+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('non vel', 'Fiction', 'Hildegard Lesch', 'thriller', '2017-01-02T22:19:37.659+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('adipisci perferendis ea', 'Fiction', 'Kamron Senger', 'science fiction', '2019-12-09T11:53:10.136+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ipsa enim quis', 'Fiction', 'Adella Hackett', 'historical', 
'2002-11-19T06:31:24.205+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('omnis et', 'Fiction', 'Maribel Fritsch', 'fantasy', '2013-07-14T14:18:59.458+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('labore rerum ut', 'Fiction', 'Maribel Fritsch', 'fantasy', '2019-02-19T23:45:51.633+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('qui tempore sed sint provident ut', 'Fiction', 'Maribel Fritsch', 'fantasy', '2016-02-27T01:12:56.194+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('optio et quia iure quia at', 'Fiction', 'Ardith Dietrich', 'horror', '2011-05-21T16:04:59.862+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('at placeat quisquam fugiat', 'Fiction', 'Chelsie Gerlach', 'dystopian', '2003-05-03T12:38:10.051+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('sit alias', 'Fiction', 'Chelsie Gerlach', 'dystopian', '2019-02-22T09:59:23.732+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('laudantium voluptas', 'Fiction', 'Zackery Dickinson', 'mystery', '2006-03-25T18:33:41.908+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('laborum quia soluta aut rerum sed', 'Fiction', 'Zackery Dickinson', 'mystery', '2009-12-01T14:08:06.654+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('consectetur quibusdam placeat facilis voluptas', 'Fiction', 
'Eda Lubowitz', 'science fiction', '2020-09-26T02:33:43.174+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('et adipisci necessitatibus aperiam commodi', 'Fiction', 'Haven Lehner', 'science fiction', '2011-04-27T08:26:47.669+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('non vel', 'Fiction', 'Haven Lehner', 'science fiction', '2012-01-31T13:38:40.465+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('quisquam nihil quibusdam doloribus molestiae', 'Fiction', 'Jairo Flatley', 'fantasy', '2011-06-07T07:05:31.616+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('autem voluptas soluta molestiae quae', 'Fiction', 'Jairo Flatley', 'fantasy', '2010-05-27T05:46:04.053+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('sit excepturi', 'Fiction', 'Jairo Flatley', 'fantasy', '2003-08-22T12:07:46.886+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('iste praesentium rerum maxime', 'Fiction', 'Shayna Shields', 'literary fiction', '2011-03-23T16:12:05.844+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('sed sapiente nisi nihil laborum', 'Fiction', 'Shayna Shields', 'literary fiction', '2021-09-03T00:44:40.909+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('rerum dolor', 'Fiction', 'Shayna Shields', 'literary fiction', '2017-08-31T13:18:14.009+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('illum est molestias velit quis iure', 'Fiction', 'Monroe Hahn', 'mystery', '2009-10-07T23:47:34.840+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ea aliquid blanditiis', 'Fiction', 'Monroe Hahn', 'mystery', '2004-09-10T15:57:20.058+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('nisi quia delectus autem in', 'Fiction', 'Monroe Hahn', 'mystery', '2018-02-19T19:43:27.830+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('natus quia ut quas', 'Fiction', 'Jaren Schaefer', 'literary 
fiction', '2002-05-08T14:54:57.508+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('voluptas labore aliquam ut et earum', 'Fiction', 'Stefanie Bednar', 'historical', '2019-04-28T18:11:41.200+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('rerum error est qui', 'Fiction', 'Stefanie Bednar', 'historical', '2019-06-06T01:28:32.178+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('et voluptatem aliquid repellendus', 'Fiction', 'Stefanie Bednar', 'historical', '2010-01-11T11:48:26.297+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('necessitatibus et minus earum', 'Fiction', 'Devon Grady', 'western', '2010-09-22T15:57:55.046+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('aut quo dolorem', 'Fiction', 'Devon Grady', 'western', '2015-07-30T19:04:58.514+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('et atque recusandae rerum quae', 'Fiction', 'Sister Klocko', 'mystery', '2016-06-19T11:53:10.083+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('est veniam similique hic soluta veniam', 'Fiction', 'Sister 
Klocko', 'mystery', '2021-01-20T11:51:51.482+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('non quasi sit dolores laborum', 'Fiction', 'Ola Hilll', 'mystery', '2003-03-21T22:22:49.630+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('quaerat molestiae autem voluptates distinctio', 'Fiction', 'Ola Hilll', 'mystery', '2013-02-08T08:37:12.789+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('nihil autem veniam quo cupiditate suscipit', 'Fiction', 'Ola Hilll', 'mystery', '2006-07-25T20:33:43.191+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('minima et', 'Fiction', 'Johanna Hahn', 'thriller', '2006-01-17T05:44:02.267+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('et repellat', 'Fiction', 'Luther Lehner', 'historical', '2020-02-12T15:35:18.982+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('quos ea', 'Fiction', 'Luther Lehner', 'historical', '2005-09-28T02:59:16.221+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('excepturi suscipit perspiciatis animi deserunt', 'Fiction', 
'Ardith Schaden', 'literary fiction', '2010-03-12T11:12:09.214+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('pariatur vel dolores', 'Fiction', 'Ardith Schaden', 'literary fiction', '2019-10-07T16:41:00.370+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('autem natus et nihil magnam facilis', 'Fiction', 'Ardith Schaden', 'literary fiction', '2020-09-13T01:03:23.774+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('vitae nemo laboriosam et voluptatibus', 'Fiction', 'Ahmad Pagac', 'horror', '2016-05-01T13:23:50.408+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('in modi ut totam ea', 'Fiction', 'Gwen Goyette', 'horror', '2005-06-14T14:54:50.097+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('molestiae quia porro', 'Fiction', 'Gwen Goyette', 'horror', 
'2005-01-13T22:58:00.899+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('et soluta aut', 'Fiction', 'Gwen Goyette', 'horror', '2013-10-26T06:36:26.645+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('hic impedit aspernatur', 'Fiction', 'Mohammed Fritsch', 'dystopian', '2008-07-24T04:24:04.037+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('assumenda consequatur', 'Fiction', 'Claudia Quitzon', 'horror', '2019-01-29T04:51:53.005+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('atque nostrum eos ipsa aut provident', 'Fiction', 'Claudia Quitzon', 'horror', '2017-08-09T10:31:52.709+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('totam ex adipisci nesciunt itaque', 'Fiction', 'Claudia Quitzon', 'horror', '2016-09-08T23:48:13.245+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('officiis voluptatum consequatur', 'Non-Fiction', 'Katelin Koch', 'humour', '2020-05-30T06:46:51.314+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('consectetur consequatur', 'Non-Fiction', 'Katelin Koch', 'humour', '2014-12-30T06:56:28.717+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('at omnis aut commodi vel neque', 'Non-Fiction', 'Archibald Mertz', 'business', '2004-03-31T02:14:37.980+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('culpa hic dolore consequatur', 'Non-Fiction', 'Archibald Mertz', 'business', '2012-08-14T18:40:20.333+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('eaque id eligendi expedita', 'Non-Fiction', 'Gino Flatley', 
'history', '2017-08-28T04:44:22.075+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('eveniet aut omnis quasi vitae voluptas', 'Non-Fiction', 'Gino Flatley', 'history', '2013-05-06T02:18:11.750+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('qui quam adipisci alias atque', 'Non-Fiction', 'Gino Flatley', 'history', '2008-04-09T13:51:36.809+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('molestiae in', 'Non-Fiction', 'Heber Williamson', 'travel guide', '2017-02-07T18:37:25.992+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('corrupti tenetur', 'Non-Fiction', 'Heber Williamson', 'travel guide', '2019-07-14T17:06:36.761+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ut quisquam officia qui nemo sunt', 'Non-Fiction', 'Yesenia 
Nicolas', 'business', '2015-12-20T00:58:31.725+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('natus laboriosam', 'Non-Fiction', 'Gilberto Walter', 'history', '2017-01-02T14:19:33.875+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('corporis quos repellendus sapiente eveniet', 'Non-Fiction', 
'Gilberto Walter', 'history', '2013-10-11T14:35:26.738+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('facilis ut', 'Non-Fiction', 'Alexandro Schuster', 'travel guide', '2012-01-11T02:32:36.994+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('harum hic', 'Non-Fiction', 'Libbie Bradtke', 'humour', '2007-04-10T20:39:16.323+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('molestiae quaerat', 'Non-Fiction', 'Libbie Bradtke', 'humour', '2018-10-07T03:18:51.903+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('facere repellendus', 'Non-Fiction', 'Dewitt Hauck', 'history', '2016-05-14T13:30:58.198+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('est quia neque molestias', 'Non-Fiction', 'Nick Russel', 'history', '2019-07-07T09:52:06.577+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('dolorum inventore est veniam id', 'Non-Fiction', 'Nick Russel', 'history', '2006-01-06T17:38:24.318+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('molestiae rerum in voluptas commodi', 'Non-Fiction', 'Isabelle Auer', 'philosophy', '2009-02-01T00:39:20.149+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('id fugit quia est ipsa quibusdam', 'Non-Fiction', 'Holly Greenholt', 'history', '2008-12-09T23:30:23.552+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('minima voluptatem quis ut quidem perferendis', 'Non-Fiction', 'Elwyn Stanton', 'business', '2006-06-03T21:05:25.445+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('incidunt ex rerum pariatur temporibus amet', 'Non-Fiction', 
'Elwyn Stanton', 'business', '2016-03-07T15:29:17.406+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('dolorum et nostrum natus', 'Non-Fiction', 'Elwyn Stanton', 'business', '2021-06-29T17:30:00.115+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('eaque est cupiditate ad nemo', 'Non-Fiction', 'Tevin Pagac', 'self-help', '2021-06-11T10:43:17.356+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('et voluptate laboriosam', 'Non-Fiction', 'Tevin Pagac', 'self-help', '2011-01-18T04:34:41.382+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ducimus porro quae aut aspernatur', 'Non-Fiction', 'Tevin Pagac', 'self-help', '2019-02-01T14:45:32.868+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('qui quisquam', 'Non-Fiction', 'Timothy Jast', 'biography', '2011-09-08T06:02:45.369+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('neque sunt nobis assumenda', 'Non-Fiction', 'Timothy Jast', 
'biography', '2019-09-20T04:03:48.308+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('sit suscipit qui repudiandae quia', 'Non-Fiction', 'Samantha 
Beahan', 'philosophy', '2016-12-12T01:38:27.401+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('sapiente alias impedit', 'Non-Fiction', 'Samantha Beahan', 'philosophy', '2014-07-15T18:15:14.711+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('odio recusandae', 'Non-Fiction', 'Wilma Jast', 'biography', '2017-12-30T11:44:38.638+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('iste aut nemo', 'Non-Fiction', 'Everette Cormier', 'self-help', '2019-10-23T21:48:24.119+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ut eveniet non', 'Non-Fiction', 'Everette Cormier', 'self-help', '2021-05-10T19:55:28.240+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('placeat eius consectetur architecto', 'Non-Fiction', 'Nick Labadie', 'philosophy', '2018-02-20T07:56:03.841+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('quia cumque maiores illum', 'Non-Fiction', 'Nick Labadie', 'philosophy', '2021-04-24T05:10:20.766+01:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('ratione laudantium voluptas nihil voluptatem', 'Non-Fiction', 'Nick Labadie', 'philosophy', '2014-02-26T03:05:12.242+00:00', 400);
INSERT INTO books (title, type, author, topic, "publicationDate", pages) VALUES ('dolore qui accusamus sed', 'Non-Fiction', 'Arianna Dietrich', 'biography', '2004-06-23T09:29:19.212+01:00', 400);

INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jonathan', 6, 'dog', 'Glen of Imaal Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nakia', 14, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lori', 5, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Donny', 13, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ladarius', 18, 'dog', 'Glen of Imaal Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Everette', 20, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Clare', 19, 'dog', 'Perro de Pastor Mallorquin', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Erik', 16, 'dog', 'Perro de Pastor Mallorquin', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Corene', 8, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Valerie', 8, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lenora', 3, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Larue', 16, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Carroll', 17, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Milford', 13, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Karine', 10, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Asha', 4, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Garth', 5, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Davin', 8, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kelley', 2, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lexi', 9, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Bethany', 16, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yessenia', 4, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hope', 10, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brock', 3, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ewald', 7, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jeffry', 17, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kaley', 18, 'dog', 'Drentse Patrijshond', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kennith', 15, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dave', 7, 'dog', 'Drentse Patrijshond', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Charlene', 1, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maia', 19, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yesenia', 8, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Keara', 10, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Garth', 2, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meredith', 1, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Genevieve', 18, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kathryne', 9, 'dog', 'Drentse Patrijshond', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jessy', 6, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Olga', 19, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jess', 11, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reese', 9, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meda', 17, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nyasia', 2, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Merle', 18, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hosea', 16, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Estrella', 18, 'dog', 'Australian Stumpy Tail Cattle Dog', true);        
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Camilla', 14, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Laila', 11, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lucius', 17, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Darren', 14, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ole', 12, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Afton', 8, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Coy', 6, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('London', 9, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Salvatore', 5, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Angelo', 4, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Shakira', 13, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Zula', 11, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brennon', 18, 'dog', 'Lupo Italiano', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Liana', 15, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Unique', 2, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dedric', 9, 'dog', 'Lupo Italiano', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Diego', 8, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mike', 2, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meaghan', 18, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Berniece', 1, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yessenia', 16, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janet', 4, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Giuseppe', 10, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Laney', 18, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Christophe', 11, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Holly', 18, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kip', 9, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Oren', 11, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Queen', 4, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kianna', 2, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mariane', 16, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Talia', 8, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dave', 10, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Adelbert', 5, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ronaldo', 13, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Edythe', 6, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Charlene', 18, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lurline', 20, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Madelynn', 18, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ignacio', 9, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lucinda', 2, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Audreanne', 11, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rasheed', 19, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deshawn', 12, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alphonso', 12, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maxie', 11, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rupert', 16, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jerrell', 8, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Xander', 9, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kelton', 9, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Etha', 20, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reba', 11, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eliseo', 18, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Freeman', 1, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deshaun', 9, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jane', 14, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Garrick', 20, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Zachary', 14, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Keon', 8, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lisa', 14, 'cat', 'Chausie', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ashley', 6, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rowan', 20, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jessyca', 20, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Tess', 3, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Josefa', 4, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janae', 2, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Darby', 3, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vernie', 4, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vernon', 16, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Barbara', 6, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Natalie', 10, 'cat', 'American Bobtail', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Miguel', 8, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Henry', 3, 'cat', 'American Bobtail', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kara', 17, 'cat', 'American Bobtail', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dante', 13, 'snake', 'Black headed python', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brandon', 20, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janessa', 17, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Bethel', 10, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Katlynn', 10, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Amanda', 1, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hildegard', 5, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gerson', 10, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yasmin', 10, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kailey', 3, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Albina', 7, 'snake', 'Rhinoceros viper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rodolfo', 5, 'snake', 'Rhinoceros viper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Heloise', 1, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Boris', 18, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcelle', 3, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Grace', 3, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kaya', 18, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Olga', 2, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nyasia', 5, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ivah', 20, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hollie', 8, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deon', 7, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Fabian', 2, 'horse', 'Cerbat Mustang', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jacynthe', 6, 'horse', 'Cerbat Mustang', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jana', 13, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Graciela', 12, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eladio', 2, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Pansy', 5, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janie', 2, 'horse', 'Cerbat Mustang', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Genevieve', 19, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Buford', 17, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jensen', 2, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Martina', 15, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maida', 5, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Sophie', 14, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cornell', 20, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Murray', 8, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Danial', 12, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marlee', 19, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Johathan', 20, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maurice', 9, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Andreane', 3, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Sarai', 2, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kara', 2, 'horse', 'Cavallo Romano della Maremma Laziale', false);       
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Erick', 2, 'horse', 'Cavallo Romano della Maremma Laziale', true);       
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Monserrat', 14, 'horse', 'Cavallo Romano della Maremma Laziale', false); 
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hosea', 19, 'horse', 'Cavallo Romano della Maremma Laziale', true);      
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reggie', 3, 'horse', 'Cavallo Romano della Maremma Laziale', false);     
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Leonor', 12, 'horse', 'Cavallo Romano della Maremma Laziale', true);     
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lillian', 15, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brielle', 13, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Myrtie', 9, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arvilla', 6, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alejandra', 20, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vicky', 11, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Favian', 8, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kitty', 17, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hoyt', 3, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gustave', 9, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ransom', 4, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mack', 9, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ethelyn', 16, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcellus', 12, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lizeth', 3, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ian', 2, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elvis', 4, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Salvador', 12, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rosamond', 7, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Velma', 11, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Zoey', 6, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Julie', 12, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Carissa', 19, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Sherwood', 13, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Grady', 5, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brando', 7, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jessyca', 15, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Avis', 17, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gabrielle', 3, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Oran', 6, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jorge', 8, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dennis', 4, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Horacio', 16, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eusebio', 7, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eleonore', 14, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ada', 14, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Adolphus', 7, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Princess', 4, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Erik', 5, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Trystan', 4, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Randal', 20, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Leon', 15, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Roscoe', 4, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cleveland', 2, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Don', 1, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Helene', 5, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Raina', 15, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Loraine', 3, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elta', 5, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Esther', 7, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meghan', 19, 'horse', 'Monterufolino', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Terrence', 17, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Wilford', 1, 'horse', 'Monterufolino', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Murl', 1, 'horse', 'Monterufolino', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kirsten', 13, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Breana', 13, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lawson', 17, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Camryn', 6, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Allene', 8, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cleve', 14, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hassan', 9, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Earl', 4, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kane', 14, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ferne', 11, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hermann', 4, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Aurelie', 9, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jared', 1, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alexis', 19, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dakota', 12, 'bird', 'Bristle-thighed Curlew', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mariela', 16, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Roxanne', 6, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Muhammad', 2, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Amely', 16, 'bird', 'Bristle-thighed Curlew', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Breana', 10, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Giovanni', 14, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Destany', 7, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brisa', 6, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Margarett', 11, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Curtis', 20, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alene', 15, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cordelia', 19, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcellus', 8, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Catherine', 20, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Laurine', 18, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nasir', 13, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Francisca', 12, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Name', 5, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Madyson', 11, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Johnathon', 14, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Abbey', 14, 'bird', 'House Finch', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dave', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Angelita', 7, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Leda', 15, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Fay', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elmore', 13, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Bettye', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Braeden', 4, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Taryn', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Green', 15, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cassandra', 14, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jalon', 15, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jordan', 19, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Heather', 3, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arlene', 14, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Giles', 10, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Johnson', 17, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Neal', 20, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arnoldo', 7, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jazmin', 20, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Myrtle', 14, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nestor', 14, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Unique', 8, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcella', 2, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jennifer', 4, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Joan', 17, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ethan', 9, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maiya', 3, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Efren', 17, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nat', 16, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marquise', 11, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deangelo', 20, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Therese', 3, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brandy', 16, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Adrain', 8, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elisa', 5, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eladio', 9, 'bird', 'Great-tailed Grackle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elissa', 19, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maggie', 19, 'bird', 'Great-tailed Grackle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nichole', 18, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gladys', 7, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Walton', 19, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lucious', 4, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reva', 18, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Magali', 2, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kailee', 10, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Drake', 11, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mae', 15, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Steve', 9, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rick', 10, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Florida', 20, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jeff', 2, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alessandro', 20, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Tod', 11, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vergie', 13, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eloisa', 12, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hulda', 9, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Pablo', 17, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gianni', 20, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maureen', 16, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Enrico', 11, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Karelle', 19, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ricardo', 12, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Opal', 17, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cleo', 8, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Israel', 17, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Austin', 20, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Courtney', 5, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yolanda', 12, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janessa', 10, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rickie', 6, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kaia', 7, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mac', 17, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Katlyn', 9, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arely', 20, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kevin', 19, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ansley', 18, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Corbin', 19, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jazmyne', 8, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ralph', 15, 'rabbit', 'Florida White', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yasmin', 16, 'rabbit', 'Florida White', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Joan', 4, 'rabbit', 'Florida White', true);
  `;
    await client.query(sql);
  })
;
